version: '3.8'

services: 
  api:
    build: 
      context: .
    container_name: api
    restart: unless-stopped
    ports: 
      - "${PORT}:${PORT}"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://api:${PORT}/api/status || exit 1
      interval: 10s
      timeout: 3s
      retries: 5 

  db:
    container_name: db
    image: postgres:11.16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 5 
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: